### ISSUE TITLE
cctk in nixpkgs?

### ISSUE THREAD

**Issue by hacker1024** [RyanGibb/nixos#1] opened 2022-11-09 09:45 UTC
Hi, thanks for publishing your work!

The `cctk` package will be very useful, but is a little hard to use on non-flake systems.
Would you consider making a PR to add it into nixpkgs?

**Comment by RyanGibb** [comment] 2022-11-09 09:52
No problem!

I do want to upstream it, but unfortunately it depends on a [fork](https://git.sr.ht/~raphi/patchelf/commit/9079354d2b94050f38594b5fab5f764f73e4b7e0) of `patchelf` that adds the `--replace-symbol` command. The author of that fork does plan to upstream it at some point, but there's no ETA. See here for a discussion: https://discourse.nixos.org/t/writing-derivation-for-binary-driver-that-accesses-hard-coded-paths-in-the-fhs/22969/4?u=ryang

**Comment by RyanGibb** [comment] 2022-11-09 12:11
Looks like the issue is being tracked here https://github.com/NixOS/patchelf/issues/416.

I've tried using `LD_PRELOAD` and Nixpkgs' `libredirect` but it doesn't propagate (from cctk) to loading of shared libraries (that cctk uses): https://discourse.nixos.org/t/writing-derivation-for-binary-driver-that-accesses-hard-coded-paths-in-the-fhs/22969/7?u=ryang

**Comment by RyanGibb** [comment] 2023-03-03 13:31
https://github.com/RyanGibb/nixos/commit/62a7d093e617b37909f3713bd37b068b3e65e18a goes some way towards using upstreamed support for rewriting dynamic symbols, but it's currently failing with:
```
patchelf: error: Span access out of range.
```

**Comment by RyanGibb** [comment] 2023-03-07 10:36
Currently pending on https://github.com/NixOS/patchelf/pull/473, then I can upstream this.

**Comment by RyanGibb** [comment] 2023-11-07 18:06
Closed by https://github.com/NixOS/nixpkgs/pull/260715

**Comment by RyanGibb** [comment] 2023-11-07 18:07
Didn't even take a year :-)

**Closed as completed by RyanGibb** 2023-11-07 18:06 UTC
